# @license
# Copyright 2025-2026 Open Home Foundation
# SPDX-License-Identifier: Apache-2.0

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TZ: ${TZ:-America/Los_Angeles}
        GIT_DELTA_VERSION: "0.18.2"
        ZSH_IN_DOCKER_VERSION: "1.2.0"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ..:/matterjs-server:cached
      - node-modules:/matterjs-server/node_modules
      - claude-code-config:/home/node/.claude
      - claude-code-bashhistory:/commandhistory
    networks:
      - "matter"
    ports:
      - "5580:5580"
    command: "sleep infinity"

volumes:
  node-modules:
  claude-code-config:
  claude-code-bashhistory:

networks:
  matter:
    enable_ipv6: true
